@ScanQrApi_HostAddress = http://localhost:5026

GET {{ScanQrApi_HostAddress}}/weatherforecast/
Accept: application/json

###

GET http://172.16.1.150:5026/persons/person-information-message
Accept: application/json

###